# Generated by Django 2.0.1 on 2019-01-14 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Наименование')),
                ('main_image', models.URLField(verbose_name='Иконка')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'ordering': ('order',),
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Когда')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'ordering': ('name', '-date'),
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Когда')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Lesson')),
            ],
            options={
                'verbose_name': 'Подписка',
                'ordering': ('-lesson__date', '-lesson', 'subscriber'),
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Подписчик',
                'ordering': ('last_name', 'first_name', 'username'),
                'verbose_name_plural': 'Подписчики',
                'indexes': [],
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Subscriber'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name',)},
        ),
    ]
