# Generated by Django 2.0.1 on 2019-01-20 19:33

import datetime
import dist_learn_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название курса')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='#')),
                ('main_image', models.FileField(default='undef.png', upload_to=dist_learn_app.models.get_upload_path, verbose_name='Иконка курса')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'verbose_name': 'Курс',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование урока')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время проведения урока')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание урока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name_plural': 'Уроки',
                'verbose_name': 'Урок',
                'ordering': ('-date', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'course')},
        ),
    ]
