# Generated by Django 2.0.1 on 2019-01-14 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dist_learn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='main_image',
            field=models.FilePathField(default='undef.png', verbose_name='Иконка курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время проведения урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование урока'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='дата подписи'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Subscriber', verbose_name='Подписчик'),
        ),
    ]
