# Generated by Django 2.0.1 on 2019-01-17 21:40

import dist_learn_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dist_learn_app', '0002_auto_20190114_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-date', 'name'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='main_image',
            field=models.FileField(default='undef.png', upload_to=dist_learn_app.models.get_upload_path, verbose_name='Иконка курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание урока'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'course')},
        ),
    ]
