# Generated by Django 2.0.1 on 2019-01-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('dist_learn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='дата подписи')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dist_learn_app.Lesson', verbose_name='Урок')),
            ],
            options={
                'ordering': ('-lesson__date', '-lesson', 'subscriber'),
                'verbose_name_plural': 'Подписки',
                'verbose_name': 'Подписка',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
            ],
            options={
                'ordering': ('last_name', 'first_name', 'username'),
                'verbose_name_plural': 'Подписчики',
                'indexes': [],
                'proxy': True,
                'verbose_name': 'Подписчик',
            },
            bases=('auth.user',),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Subscriber', verbose_name='Подписчик'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'lesson')},
        ),
    ]
